id: P004404
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:38.056948
source_metadata:
  id: bdr:W1KG8725
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་དཀའ་འགྲེལ་དགོངས་པ་རབ་གསལ།
  author: ''
  volumes:
    e57c760458d746599658c002930fe7a9:
      image_group_id: I1KG8764
      title: ''
      volume_number: 1
      total_pages: 618
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
