id: IC09BAB7D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T17:36:16+00:00'
last_modified: '2022-06-07T22:38:07.897886+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8725
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་དཀའ་འགྲེལ་དགོངས་པ་རབ་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E104:
      image_group_id: I1KG8764
      title: ''
      total_pages: 618
      order: 1
      base_file: E104.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
